include:
    - compose/initializer.yml
    - compose/frontend.yml
    - compose/sincro-rtc.yml
    - compose/speech-extractor.yml
    - compose/speech-recognizer.yml
    - compose/text-processor.yml
    - compose/voice-synthesizer.yml
    - compose/consul-server.yml
    - compose/minio.yml
    - compose/redis.yml
    - compose/mediamtx.yml

networks:
    sincromisor-net:
