---
VoiceSynthesizer:
    EnableRedis: true
    DefaultStyleID: 0
    PrePhonemeLength: 0.1
    PostPhonemeLength: 0.0
Worker:
    Sincromisor:
        - host: 0.0.0.0
          port: 8001
          url: http://127.0.0.1:8001/
          forwarded-allow-ips: 10.39.2.1
          launch: true
    SpeechExtractor:
        - host: 0.0.0.0
          port: 8003
          url: ws://127.0.0.1:8003/
          launch: true
    SpeechRecognizer:
        - host: 0.0.0.0
          port: 8004
          url: ws://127.0.0.1:8004/
          launch: true
    VoiceSynthesizer:
        - host: 0.0.0.0
          port: 8005
          url: ws://127.0.0.1:8005/
          launch: true
Redis:
    - host: localhost
      port: 6379
VoiceVox:
    - host: localhost
      port: 50021
RTCIceServers:
    - urls: stun:stun.negix.org:3478
    #- urls: turn:turn.negix.org:3478
    #  username: gloria
    #  credential: SECRET_KEY
