include:
    - initializer.yml

services:
    sincro-client:
        profiles:
            - full
            - frontend
        build:
            context: ..
            dockerfile: ./Docker/sincro-client/Dockerfile
        image: ${SINCRO_REGISTRY_NAME}/sincro-client:latest
        ports:
            - 80:80/tcp
            - 443:443/tcp
            - 443:443/udp
        volumes:
            - ../configs/Caddyfile:/etc/caddy/Caddyfile:ro
        networks:
            - sincromisor-net
        deploy:
            restart_policy:
                condition: any
                delay: 10s
        depends_on:
            service-initializer:
                condition: service_completed_successfully

networks:
    sincromisor-net:
