services:
    service-initializer:
        profiles:
            - full
            - full-experimental
            - frontend
            - backend
            - backend-experimental
        build:
            context: ..
            dockerfile: ./Docker/service-initializer/Dockerfile
        image: sincromisor/service-initializer
        volumes:
            - ../configs/config.yml:/opt/sincromisor/configs/config.yml:rw
            - ../volumes:/volumes
        networks:
            - sincromisor-net

networks:
    sincromisor-net:
