services:
    sincro-redis:
        profiles:
            - full
            - backend
            - external
        image: ${SINCRO_REGISTRY_NAME}/redis:latest
        build:
            context: ..
            dockerfile: ./Docker/redis/Dockerfile
        ports:
            - 6379:6379/tcp
        networks:
            - sincromisor-net
        environment:
            - SINCRO_CONSUL_AGENT_HOST=consul-agent-redis
            - SINCRO_CONSUL_AGENT_PORT=8500
        command: /start-redis.sh
        deploy:
            restart_policy:
                condition: any
                delay: 10s
        depends_on:
            consul-agent-redis:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 5s
            retries: 5

    consul-agent-redis:
        profiles:
            - full
            - backend
            - external
        image: hashicorp/consul:latest
        command:
            [
                "agent",
                "-retry-join=${SINCRO_CONSUL_SERVER_HOST}",
                "-client=0.0.0.0",
            ]
        volumes:
            - consul-agent-redis-data:/consul/data
        networks:
            - sincromisor-net
        deploy:
            restart_policy:
                condition: any
                delay: 10s
        healthcheck:
            test: ["CMD", "consul", "members"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    consul-agent-redis-data:

networks:
    sincromisor-net:
