services:
    speech-extractor:
        profiles:
            - full
            - full-experimental
            - backend
            - backend-experimental
        build:
            context: ..
            dockerfile: ./Docker/speech-extractor/Dockerfile
        image: sincromisor/speech-extractor:latest
        ports:
            - 8002:8002/tcp
        networks:
            - sincromisor-net
        environment:
            - SINCRO_EXTRACTOR_HOST=${SINCRO_EXTRACTOR_HOST}
            - SINCRO_EXTRACTOR_PORT=${SINCRO_EXTRACTOR_PORT}
            - SINCRO_EXTRACTOR_PUBLIC_BIND_HOST=${SINCRO_EXTRACTOR_PUBLIC_BIND_HOST}
            - SINCRO_EXTRACTOR_PUBLIC_BIND_PORT=${SINCRO_EXTRACTOR_PUBLIC_BIND_PORT}
            - SINCRO_CONSUL_AGENT_HOST=${SINCRO_CONSUL_AGENT_HOST}
            - SINCRO_CONSUL_AGENT_PORT=${SINCRO_CONSUL_AGENT_PORT}
        deploy:
            restart_policy:
                condition: any
                delay: 10s

networks:
    sincromisor-net:
