services:
    speech-extractor:
        profiles:
            - full
            - backend
        build:
            context: ..
            dockerfile: ./Docker/speech-extractor/Dockerfile
        image: ${SINCRO_REGISTRY_NAME}/speech-extractor:latest
        ports:
            - 8002:8002/tcp
        networks:
            - sincromisor-net
        environment:
            - SINCRO_EXTRACTOR_HOST=${SINCRO_EXTRACTOR_HOST}
            - SINCRO_EXTRACTOR_PORT=${SINCRO_EXTRACTOR_PORT}
            - SINCRO_EXTRACTOR_PUBLIC_BIND_HOST=${SINCRO_EXTRACTOR_PUBLIC_BIND_HOST}
            - SINCRO_EXTRACTOR_PUBLIC_BIND_PORT=${SINCRO_EXTRACTOR_PUBLIC_BIND_PORT}
            - SINCRO_CONSUL_AGENT_HOST=consul-agent-extractor
            - SINCRO_CONSUL_AGENT_PORT=8500
        deploy:
            restart_policy:
                condition: any
                delay: 10s
        depends_on:
            consul-agent-extractor:
                condition: service_healthy

    consul-agent-extractor:
        profiles:
            - full
            - backend
        image: hashicorp/consul:latest
        command:
            [
                "agent",
                "-retry-join=${SINCRO_CONSUL_SERVER_HOST}",
                "-client=0.0.0.0",
            ]
        volumes:
            - consul-agent-extractor-data:/consul/data
        networks:
            - sincromisor-net
        deploy:
            restart_policy:
                condition: any
                delay: 10s
        healthcheck:
            test: ["CMD", "consul", "members"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    consul-agent-extractor-data:

networks:
    sincromisor-net:
