services:
    sincro-redis:
        profiles:
            - full
            - backend
            - external
        image: ${SINCRO_REGISTRY_NAME}/redis:latest
        build:
            context: ..
            dockerfile: ./Docker/redis/Dockerfile
        ports:
            - 6379:6379/tcp
        networks:
            - sincromisor-net
        deploy:
            restart_policy:
                condition: any
                delay: 10s
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 5s
            retries: 5

    sincro-minio:
        profiles:
            - full
            - backend
            - external
        image: minio/minio:latest
        ports:
            - 9000:9000/tcp
            - 9001:9001/tcp
        environment:
            - MINIO_ROOT_USER=${SINCRO_MINIO_ROOT_USER}
            - MINIO_ROOT_PASSWORD=${SINCRO_MINIO_ROOT_PASSWORD}
        volumes:
            - ../volumes/minio:/data
        command: server /data --console-address ":9001"
        networks:
            - sincromisor-net
        deploy:
            restart_policy:
                condition: any
                delay: 10s
        healthcheck:
            test: ["CMD", "mc", "ready", "local"]
            interval: 5s
            timeout: 5s
            retries: 5

networks:
    sincromisor-net:
