services:
    text-processor:
        profiles:
            - full
            - full-experimental
            - backend
            - backend-experimental
        build:
            context: ..
            dockerfile: ./Docker/text-processor/Dockerfile
        image: ${SINCRO_REGISTRY_NAME}/text-processor:latest
        ports:
            - 8004:8004/tcp
        networks:
            - sincromisor-net
        environment:
            - SINCRO_PROCESSOR_HOST=${SINCRO_PROCESSOR_HOST}
            - SINCRO_PROCESSOR_PORT=${SINCRO_PROCESSOR_PORT}
            - SINCRO_PROCESSOR_PUBLIC_BIND_HOST=${SINCRO_PROCESSOR_PUBLIC_BIND_HOST}
            - SINCRO_PROCESSOR_PUBLIC_BIND_PORT=${SINCRO_PROCESSOR_PUBLIC_BIND_PORT}
            - SINCRO_CONSUL_AGENT_HOST=${SINCRO_CONSUL_AGENT_HOST}
            - SINCRO_CONSUL_AGENT_PORT=${SINCRO_CONSUL_AGENT_PORT}
            - SINCRO_PROCESSOR_DIFY_URL=${SINCRO_PROCESSOR_DIFY_URL}
            - SINCRO_PROCESSOR_DIFY_TOKEN=${SINCRO_PROCESSOR_DIFY_TOKEN}
        deploy:
            restart_policy:
                condition: any
                delay: 10s
        depends_on:
            service-initializer:
                condition: service_completed_successfully

networks:
    sincromisor-net:
