services:
    voice-synthesizer:
        profiles:
            - full
            - backend
        build:
            context: ..
            dockerfile: ./Docker/voice-synthesizer/Dockerfile
        image: ${SINCRO_REGISTRY_NAME}/voice-synthesizer:latest
        ports:
            - 8005:8005/tcp
        networks:
            - sincromisor-net
        environment:
            - SINCRO_SYNTHESIZER_HOST=${SINCRO_SYNTHESIZER_HOST}
            - SINCRO_SYNTHESIZER_PORT=${SINCRO_SYNTHESIZER_PORT}
            - SINCRO_SYNTHESIZER_PUBLIC_BIND_HOST=${SINCRO_SYNTHESIZER_PUBLIC_BIND_HOST}
            - SINCRO_SYNTHESIZER_PUBLIC_BIND_PORT=${SINCRO_SYNTHESIZER_PUBLIC_BIND_PORT}
            - SINCRO_CONSUL_AGENT_HOST=consul-agent-synthesizer
            - SINCRO_CONSUL_AGENT_PORT=8500
            - SINCRO_MINIO_ACCESS_KEY=${SINCRO_MINIO_ACCESS_KEY}
            - SINCRO_MINIO_SECRET_KEY=${SINCRO_MINIO_SECRET_KEY}
            - SINCRO_SYNTHESIZER_VOICEVOX_DEFAULT_STYLE_ID=${SINCRO_SYNTHESIZER_VOICEVOX_DEFAULT_STYLE_ID}
        deploy:
            restart_policy:
                condition: any
                delay: 10s
        depends_on:
            consul-agent-synthesizer:
                condition: service_healthy
            sincro-voicevox:
                condition: service_healthy
        healthcheck:
            test:
                [
                    "CMD",
                    "curl",
                    "http://localhost:8005/api/v1/VoiceSynthesizer/statuses",
                ]
            interval: 10s
            timeout: 5s
            retries: 15

    sincro-voicevox:
        profiles:
            - full
            - backend
        image: ${SINCRO_REGISTRY_NAME}/voicevox:latest
        build:
            context: ..
            dockerfile: ./Docker/voicevox/Dockerfile
        ports:
            - 50021:50021/tcp
        networks:
            - sincromisor-net
        environment:
            - SINCRO_VOICEVOX_HOST=${SINCRO_VOICEVOX_HOST}
            - SINCRO_VOICEVOX_PORT=${SINCRO_VOICEVOX_PORT}
            - SINCRO_CONSUL_AGENT_HOST=consul-agent-synthesizer
            - SINCRO_CONSUL_AGENT_PORT=8500
        deploy:
            restart_policy:
                condition: any
                delay: 10s
        depends_on:
            consul-agent-synthesizer:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "curl", "http://localhost:50021/version"]
            interval: 10s
            timeout: 5s
            retries: 5

    consul-agent-synthesizer:
        profiles:
            - full
            - backend
        image: hashicorp/consul:latest
        command:
            [
                "agent",
                "-retry-join=${SINCRO_CONSUL_SERVER_HOST}",
                "-client=0.0.0.0",
            ]
        volumes:
            - consul-agent-synthesizer-data:/consul/data
        networks:
            - sincromisor-net
        deploy:
            restart_policy:
                condition: any
                delay: 10s
        healthcheck:
            test: ["CMD", "consul", "members"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    consul-agent-synthesizer-data:

networks:
    sincromisor-net:
