services:
    voice-synthesizer:
        profiles:
            - full
            - full-experimental
            - backend
            - backend-experimental
        build:
            context: ..
            dockerfile: ./Docker/voice-synthesizer/Dockerfile
        image: ${SINCRO_REGISTRY_NAME}/voice-synthesizer:latest
        ports:
            - 8005:8005/tcp
        networks:
            - sincromisor-net
        environment:
            - SINCRO_SYNTHESIZER_HOST=${SINCRO_SYNTHESIZER_HOST}
            - SINCRO_SYNTHESIZER_PORT=${SINCRO_SYNTHESIZER_PORT}
            - SINCRO_SYNTHESIZER_PUBLIC_BIND_HOST=${SINCRO_SYNTHESIZER_PUBLIC_BIND_HOST}
            - SINCRO_SYNTHESIZER_PUBLIC_BIND_PORT=${SINCRO_SYNTHESIZER_PUBLIC_BIND_PORT}
            - SINCRO_CONSUL_AGENT_HOST=${SINCRO_CONSUL_AGENT_HOST}
            - SINCRO_CONSUL_AGENT_PORT=${SINCRO_CONSUL_AGENT_PORT}
            - SINCRO_REDIS_HOST=${SINCRO_REDIS_HOST}
            - SINCRO_REDIS_PORT=${SINCRO_REDIS_PORT}
            - SINCRO_SYNTHESIZER_VOICEVOX_HOST=${SINCRO_SYNTHESIZER_VOICEVOX_HOST}
            - SINCRO_SYNTHESIZER_VOICEVOX_PORT=${SINCRO_SYNTHESIZER_VOICEVOX_PORT}
            - SINCRO_SYNTHESIZER_VOICEVOX_DEFAULT_STYLE_ID=${SINCRO_SYNTHESIZER_VOICEVOX_DEFAULT_STYLE_ID}
        deploy:
            restart_policy:
                condition: any
                delay: 10s

    sincro-voicevox:
        profiles:
            - full
            - full-experimental
            - backend
            - external
        image: ${SINCRO_REGISTRY_NAME}/voicevox:latest
        build:
            context: ..
            dockerfile: ./Docker/voicevox/Dockerfile
        ports:
            - 50021:50021/tcp
        networks:
            - sincromisor-net
        deploy:
            restart_policy:
                condition: any
                delay: 10s

networks:
    sincromisor-net:
