services:
    voice-synthesizer:
        profiles:
            - full
            - full-experimental
            - backend
            - backend-experimental
        build:
            context: ..
            dockerfile: ./Docker/voice-synthesizer/Dockerfile
        image: ${SINCRO_REGISTRY_NAME}/voice-synthesizer:latest
        ports:
            - 8005:8005/tcp
        networks:
            - sincromisor-net
        environment:
            - SINCRO_SYNTHESIZER_HOST=${SINCRO_SYNTHESIZER_HOST}
            - SINCRO_SYNTHESIZER_PORT=${SINCRO_SYNTHESIZER_PORT}
            - SINCRO_SYNTHESIZER_PUBLIC_BIND_HOST=${SINCRO_SYNTHESIZER_PUBLIC_BIND_HOST}
            - SINCRO_SYNTHESIZER_PUBLIC_BIND_PORT=${SINCRO_SYNTHESIZER_PUBLIC_BIND_PORT}
            - SINCRO_CONSUL_AGENT_HOST=consul-agent-synthesizer
            - SINCRO_CONSUL_AGENT_PORT=8500
            - SINCRO_REDIS_HOST=${SINCRO_REDIS_HOST}
            - SINCRO_REDIS_PORT=${SINCRO_REDIS_PORT}
            - SINCRO_SYNTHESIZER_VOICEVOX_HOST=${SINCRO_SYNTHESIZER_VOICEVOX_HOST}
            - SINCRO_SYNTHESIZER_VOICEVOX_PORT=${SINCRO_SYNTHESIZER_VOICEVOX_PORT}
            - SINCRO_SYNTHESIZER_VOICEVOX_DEFAULT_STYLE_ID=${SINCRO_SYNTHESIZER_VOICEVOX_DEFAULT_STYLE_ID}
        deploy:
            restart_policy:
                condition: any
                delay: 10s

    sincro-voicevox:
        profiles:
            - full
            - full-experimental
            - backend
        image: ${SINCRO_REGISTRY_NAME}/voicevox:latest
        build:
            context: ..
            dockerfile: ./Docker/voicevox/Dockerfile
        ports:
            - 50021:50021/tcp
        networks:
            - sincromisor-net
        deploy:
            restart_policy:
                condition: any
                delay: 10s

    consul-agent-synthesizer:
        profiles:
            - full
            - full-experimental
            - backend
            - backend-experimental
        image: hashicorp/consul:latest
        command:
            [
                "agent",
                "-retry-join=${SINCRO_CONSUL_SERVER_HOST}",
                "-client=0.0.0.0",
            ]
        volumes:
            - consul-agent-synthesizer-data:/consul/data
        networks:
            - sincromisor-net
        deploy:
            restart_policy:
                condition: any
                delay: 10s

volumes:
    consul-agent-synthesizer-data:

networks:
    sincromisor-net:
